basic.forever(function () {
    led.plot(1, 1)
    led.plot(3, 1)
    led.plot(0, 3)
    led.plot(4, 3)
    led.plot(1, 4)
    led.plot(2, 4)
    led.plot(3, 4)
    basic.clearScreen()
    basic.pause(500)
    led.plot(1, 1)
    led.plot(3, 1)
    led.plot(1, 3)
    led.plot(2, 3)
    led.plot(3, 3)
    led.plot(0, 4)
    led.plot(4, 4)
})
